### ISSUE TITLE
undefined input value in Edge is displayed incorrectly

### ISSUE THREAD

**Issue by yuretz** [WebReflection/lighterhtml#63]
This is probably yet another Edge edge case, but when `<input>` value is `undefined`, its content is displayed as a `dt: 0.123456;`, while in Chrome and Firefox the content remains blank as expected. 
[Please see demo here](https://codepen.io/yuretz/pen/zYOEVgK).

It's easy  to work around the issue by using `null` or empty string instead of `undefined`, but I thought I would report it anyway.

**Comment by WebReflection** [comment]
I can't wait for Edge on Chrome to go out so that this stuff will stop hunting me 😅

good report, thanks for filing it. I will try to find a solution for Edge as soon as I have time, and it's weird 'cause I purposely use `== null` un my code (note, it's not strict ===) exactly to avoid worrying about `null` VS `undefined` ... but Edge, of course, is Edge ...

**Comment by yuretz** [comment]
Cool, thanks!

Yes, we all hope the Chrome version of Edge is going to be easier to be compatible with. There should be upsides to browser mono-culture, right? 😅

**Comment by WebReflection** [comment]
... because of course if you remove attributes in IE/Edge those persists forever anyway ... this was a domtagger issue, both lighterhtml and hyperHTML has been fixed.

Please let me know if that's not the case for you.

**Comment by yuretz** [comment]
Works perfectly now, thank you!
