### ISSUE TITLE
Input class attribute is reset in Edge

### ISSUE THREAD

**Issue by yuretz** [WebReflection/lighterhtml#64]
Yet another Edge-specific issue.

We are using custom-styled check boxes, radio buttons and text inputs in our app. What we have noticed is that in Edge the effective class attribute is sometimes blank, even though it's not empty in the template. Everything works as expected in Firefox and Chrome.

[Please see the demo here](https://codepen.io/yuretz/pen/dybZOpL)

**Comment by WebReflection** [comment]
Oh gosh, could you please file all bugs you know about Edge at once? 😂

Jokes a part, it takes a little while for me to test IE11/Edge (they all have same bugs with attributes, which I've learned is the part nobody at MS ever refactored) so if you know any other issue, please share ASAP so that I can tackle all at once.

**Comment by yuretz** [comment]
I don't think I have any more issues for you today 😄 
The reason why I haven't reported both last ones at once was that I wanted to be sure they are browser-related and reproducible. But I'll try to batch the similar ones together next time.

**Comment by WebReflection** [comment]
actually, current fix breaks SVG ...

**Comment by WebReflection** [comment]
OK, everything should be fine now ... like, hopefully, forever

**Comment by yuretz** [comment]
It works! Thank you so much!

**Comment by WebReflection** [comment]
I hope I haven't broken anything else now, but the fix looks like reasonable for IE/Edge only and also others.
