### ISSUE TITLE
Question about rerendering a stateful component on local state change 

### ISSUE THREAD

**Issue by yuretz** [WebReflection/lighterhtml#79]
Please take a look at [this example](https://jsfiddle.net/yuretz/Lov25dtk/). Is it a recommended/supported way of triggering a local update to a component, instead of doing [something like this](https://jsfiddle.net/yuretz/gnqht521/) where a top-level render() is being called (meaning it would traverse the whole hierarchy touching every other non-related component too) every time an update is needed? 

Most of examples I've seen use top-lever render() to update, therefore the question.

**Comment by WebReflection** [comment]
To start with, I'd probably write that as such:

```js
const {render, html} = lighterhtml;

const counter = count => html`
  <div>
    <p>You clicked ${count} times</p>
    <button onclick=${() => { update(++count); }}>
    Click me
    </button>
  </div>`;

const update = count => render(document.body, counter(count));

update(0);
```

however, _lighterhtml_ doesn't have know anything about "_statefull component_", it provides the primitives to eventually obtain that.

That being said, _lighterhtml_ never traverse anything, if not once per unique template literal and never again, meaning no DOM traversing is ever involved in any update, only holes are eventually updated so that there is a misunderstanding of how it works behind the scene, which is not by preserving renders calls, 'cause rendering a whole thing is blazing fast, so you should never care about DOM traversing, as that doesn't even happen.

> Most of examples I've seen use top-lever render() to update, therefore the question.

If you have a referenced part (i.e. `html.for(...)`) then it could handle local updates without passing through the render, and same goes if you have inner `render` calls, which is the common Custom Element case.

However, if you want to have components, I suggest you either look at [neverland](https://github.com/WebReflection/neverland/#readme) (hooks) or [heresy](https://github.com/WebReflection/heresy/#readme) (JSX like), so that with _neverland_, as example, you'll have:

```js
const {neverland: $, render, html, useState} = neverland;

const Counter = $(() => {
  const [count, update] = useState(0);
  return  html`
  <div>
    <p>You clicked ${count} times</p>
    <button onclick=${() => { update(count + 1); }}>
    Click me
    </button>
  </div>`;
});

render(document.body, Counter());
```

and all the updates happen "_locally_" without needing top-down renders.

**Comment by yuretz** [comment]
OK, thanks for your reply. 

The examples I provided are artificial, they were intentionally made as such to make the essence of what I'm asking about very obvious, so of course there are better ways to implement the counter. The question wasn't about the counter, it was about whether updates without `render()` are supported/encouraged, or are they just a side-effect of how things are currently implemented, and shouldn't be relied upon. I haven't found an answer in the documentation, so I decided to ask it here.

I know rendering the whole thing is super fast in _lighterhtml_, and that's one of its very strong points, so I don't have any performance concerns. As a user, I like the fact that I get this blazing fast performance without getting deep into details about how exactly the library achieves it. It abstracts away just the right things, and leaves the rest for me to decide. It seems to do _one thing_, it does it _right_ and it does it _fast_, what could be better? Maybe just the documentation, but the API is so small that functionality is obvious most of the time. 

My only concern was that if it's just a local component state that changes, then one might argue that it's conceptually cleaner to let component update itself without having to call any external "re-render everything" functions. In my opinion, it reduces the component's dependencies and makes things more isolated and reusable. 

When saying about "traversing", I didn't mean that _lighterhtml_ traverses something by itself, I just meant the architecture where every component function might call other component functions in its template literal parameters and so on, and if you have one `render()` at the top-level then you could update the whole tree by calling the top-level function, effectively "traversing" the whole "call tree" of components, not the DOM tree. Probably, I wasn't clear enough in this part of my question.

Regarding _neverland_, I've played with it and I think it's a cute little library, however after looking more closely at the whole "hooks" concept I came to conclusion that hooks are doing more harm than good by hiding some details of how the local component state should be managed. I think the advantages of "hooks" are very much imaginary, it's yet another flawed abstraction that doesn't capture some useful details about reality well enough.

Regarding _heresy_ in particular and Custom Elements in general, right now I don't see what I would gain by using it compared to raw _lighterhtml_, which gives me freedom and doesn't force me into the object model I don't necessarily agree with. Well, the future might prove me wrong, we will find it out when it happens 😄

**Comment by WebReflection** [comment]
The thing is, once you create a callback to update within the closure, and you invoke it each time, you're basically replicating exactly what _neverland_ would do with confined state updates, so that of course you are free to use your own pattern to create components that update a part, but the _neverland_ library already does that, so maybe you can give it a try before thinking "_hooks are bad_".

Regardless, the library needs references to know what to update, so that either you save components manually, or you let the render organize all the things for you.

There's no other way to confine updates, beside creating inner wraps, but then again, with _neverland_ the code is more elegant, those wraps are automatically handled, and you don't need to repeat the same pattern over and over, plus it composes well via its utilities (useState, useContext, etc).

Last, but not least, you don't need anymore to return a callback with _lighterhtml_, as the `html` or `svg` already returns a "_Hole_" which is handled by the render.

**Comment by yuretz** [comment]
I totally understand your arguments, but I still think hooks are too much "magic", i.e. there is a lot of implicit behavior hidden behind the scene, they are just hiding too much, meaning it's hard to reason about how to use them properly without knowing exactly how they are implemented, or you just have to blindly follow some arbitrary, non obvious rules and hope for the best. In my world things like "don't call this inside conditions", "call order is important", etc. all smell very very fishy, even though they of course have good explanations behind. For me it all looks like an attempt of a generic and abstract solution to the problem I'm not even sure I have, and then some hacky implementation details of this solution, are going to leak directly into my code. I don't like it. My closures aren't perfect, but their behavior is simple and well documented, they are clear, proven, nicely supported, subjectively easy on the eyes, and they allow me to do anything within the language rules and syntax.
And if I want to compose them, well, I do so without any remorse or hesitation. They are functions after all, they compose super nicely.

Another thing I dislike is the implicit global context, which is probably hidden behind the `$()` wrapper function. It might be the only reasonable way to emulate React hooks API, but I'm personally not convinced React's solution to the problem is the best one. 

If I was implementing something like this, I would probably pass the context around directly to the component functions and all the `useWhatever()` helpers,  again, just to make things more clear, even if repetitive.  Or, even better, turn all this helpers into context object methods, so things are even more clear and loosely coupled.

And last thing to mention, when I was starting my current project, _neverland_ library had some notice in its README hinting that you were not sure about its future, so I decided to go with pure _lighterhtml_ and add hooks later if they prove worthy.

**Comment by yuretz** [comment]
After thinking a bit more, I can now actually imagine an alternative implementation of this whole hooky thing via generators, where you would do something like
```js
function* Component() {
    const [getValue, setValue] = this.useState(0);
    
    while(true) {
        const value = yield getValue();
        yield html`<button onclick=${() => setValue(value + 1)}>
            ${`Clicked ${value} times`}
        </button>`;
    }
}
```
In this case there should no silly call order limitations, you can do pretty much whatever you please in any sequence, because there is no longer need to address your effects by their index, you could simply use references that are preserved between your rendering iterations.

**Comment by WebReflection** [comment]
@yuretz I don't think I'd code `while(true)` daily, but whatever solution you find, please don't call other solutions silly, as these already work well, it's just you not liking the way these do.

Thank.

**Comment by yuretz** [comment]
I haven't called any other solution silly, it's the hook call order limitation that I find unsatisfactory. 
I didn't mean to offend, so I apologize if my wording sounded rude.
 I highly respect your knowledge and work,  so the only thing I wanted was some technical discussion and opinion exchange, nothing more.

**Comment by WebReflection** [comment]
Right, so ... I still wouldn't write `while(true)` in the wild, it has to be hidden somehow.

```js
function Component() {
    const [getValue, setValue] = useState(0);
    return function *() {
      const value = yield getValue();
      yield html`<button onclick=${() => setValue(value + 1)}>
        ${`Clicked ${value} times`}
      </button>`;
    };
}
```

Something like above pattern would look cleaner to me, ad easier to reason about.

**Comment by yuretz** [comment]
Agree, this looks really nice and clean, with a clear separation between the declaration and usage part. It's curious how it now also looks structurally similar to a normal stateful function components with "internalized" state. Pretty cool!
